{{- range .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: {{ .name }}
 name: {{ .name }}
spec:
 replicas: 1
 selector:
   matchLabels:
     app: {{ .name }}
 strategy: {}
 template:
   metadata:
     labels:
       app: {{ .name }}
   spec:
     containers:
     - image: quay.io/rhdevelopers/bgd:1.0.0
       name: {{ .name }}
       env:
       - name: PORT
                        value: {{ .Values.containers.containerPort | quote }}
       - name: COLOR
         value: {{ .color }}
       resources: {}
       securityContext:
         allowPrivilegeEscalation: false
         capabilities:
           drop:
           - ALL
       readinessProbe:
                    httpGet:
                      path: /health/readiness # this check the application url path
                      port: {{ .Values.containers.containerPort  }} # In which port the Application is listening
                      scheme: HTTP
                    initialDelaySeconds: 1 # the time is waiting before testing the application path
                    timeoutSeconds: 1 # the time for timeout
                    periodSeconds: 10 # the amount of time to wait between checks
                    successThreshold: 1 # count to declare successful 
                    failureThreshold: 3 # count to declare failure 
       livenessProbe:
                      httpGet:
                        path: /health/liveliness
                        port: {{ .Values.containers.containerPort }}
                        scheme: HTTP
                      initialDelaySeconds: 1
                      timeoutSeconds: 1
                      periodSeconds: 10
                      successThreshold: 1
                      failureThreshold: 3
     securityContext:
       runAsNonRoot: true
       seccompProfile:
         type: RuntimeDefault
{{- end }}
